// GEC Website Constants

export const COMPANY_INFO = {
  name: "Global Educational Consultants",
  shortName: "GEC",
  tagline: "Your Pathway to Global Education",
  location: "China",
  whatsapp: "+923114999954",
  whatsappLink: "https://wa.me/923114999954",
  email: "info@gecpathways.com",
  founded: "2017",
}

export const STATS = [
  { value: 500, suffix: "+", label: "Students Guided" },
  { value: 14, suffix: "+", label: "Partner Universities" },
  { value: 95, suffix: "%", label: "Visa Success Rate" },
  { value: 8, suffix: "+", label: "Years Experience" },
]

export const NAV_LINKS = [
  {
    label: "About",
    href: "/about",
    children: [
      { label: "Our Story", href: "/about" },
      { label: "Our Team", href: "/about#team" },
      { label: "Why China", href: "/about#why-china" },
    ],
  },
  {
    label: "Programs",
    href: "/programs",
    children: [
      { label: "MBBS in China", href: "/programs/mbbs" },
      { label: "Chinese Language", href: "/programs/chinese-language" },
      { label: "Masters & PhD", href: "/programs/masters-phd" },
      { label: "Other Programs", href: "/programs/other-programs" },
    ],
  },
  {
    label: "Countries",
    href: "/countries",
    children: [
      { label: "Pakistan", href: "/countries/pakistan" },
      { label: "Yemen", href: "/countries/yemen" },
      { label: "Saudi Arabia", href: "/countries/saudi-arabia" },
      { label: "African Nations", href: "/countries/africa" },
    ],
  },
  { label: "Scholarships", href: "/scholarships" },
  { label: "Services", href: "/services" },
  { label: "Student Life", href: "/student-life" },
  { label: "Blog", href: "/blog" },
  { label: "Contact", href: "/contact" },
]

export const UNIVERSITIES = [
  {
    id: 1,
    name: "Yangtze University",
    location: "Hubei, China",
    tuitionRange: "$3,500 - $4,500/year",
    ranking: "Top 300 in China",
    pmdc: true,
    who: true,
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?q=80&w=1000&auto=format&fit=crop",
    description: "One of the oldest and most prestigious universities in Hubei Province.",
  },
  {
    id: 2,
    name: "Binzhou Medical University",
    location: "Shandong, China",
    tuitionRange: "$4,000 - $5,000/year",
    ranking: "Top Medical University",
    pmdc: true,
    who: true,
    image: "https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=1000&auto=format&fit=crop",
    description: "Renowned for its medical programs and modern facilities.",
  },
  {
    id: 3,
    name: "China Three Gorges University",
    location: "Hubei, China",
    tuitionRange: "$3,000 - $4,000/year",
    ranking: "Top 250 in China",
    pmdc: true,
    who: true,
    image: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?q=80&w=1000&auto=format&fit=crop",
    description: "Located near the famous Three Gorges Dam with excellent facilities.",
  },
  {
    id: 4,
    name: "Hubei University of Medicine",
    location: "Hubei, China",
    tuitionRange: "$3,500 - $4,500/year",
    ranking: "Top Medical School",
    pmdc: true,
    who: true,
    image: "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?q=80&w=1000&auto=format&fit=crop",
    description: "Specialized in medical education with affiliated hospitals.",
  },
  {
    id: 5,
    name: "Nanchang University",
    location: "Jiangxi, China",
    tuitionRange: "$4,500 - $5,500/year",
    ranking: "Double First-Class University",
    pmdc: true,
    who: true,
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=1000&auto=format&fit=crop",
    description: "A comprehensive university with strong medical programs.",
  },
  {
    id: 6,
    name: "Guangdong Pharmaceutical University",
    location: "Guangdong, China",
    tuitionRange: "$4,000 - $5,000/year",
    ranking: "Top Pharmaceutical",
    pmdc: true,
    who: true,
    image: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?q=80&w=1000&auto=format&fit=crop",
    description: "Specialized in pharmaceutical and medical sciences.",
  },
  {
    id: 7,
    name: "Kunming University of Science and Technology",
    location: "Yunnan, China",
    tuitionRange: "$3,800 - $4,800/year",
    ranking: "Top in Yunnan",
    pmdc: true,
    who: true,
    image: "https://images.unsplash.com/photo-1590012314607-6da599835524?q=80&w=1000&auto=format&fit=crop",
    description: "Located in the spring city with excellent climate.",
  },
  {
    id: 8,
    name: "Jiamusi University",
    location: "Heilongjiang, China",
    tuitionRange: "$3,000 - $3,800/year",
    ranking: "Affordable Option",
    pmdc: true,
    who: true,
    image: "https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?q=80&w=1000&auto=format&fit=crop",
    description: "Affordable education in Northeast China.",
  },
  {
    id: 9,
    name: "Gannan Medical University",
    location: "Jiangxi, China",
    tuitionRange: "$3,200 - $4,000/year",
    ranking: "Growing Medical School",
    pmdc: true,
    who: true,
    image: "https://images.unsplash.com/photo-1551601651-2a8555f1a136?q=80&w=1000&auto=format&fit=crop",
    description: "Known for quality medical education at affordable costs.",
  },
  {
    id: 10,
    name: "Shihezi University",
    location: "Xinjiang, China",
    tuitionRange: "$2,800 - $3,500/year",
    ranking: "211 Project University",
    pmdc: true,
    who: true,
    image: "https://images.unsplash.com/photo-1595113316349-9fa4eb24f884?q=80&w=1000&auto=format&fit=crop",
    description: "Part of China's 211 project with quality education.",
  },
  {
    id: 11,
    name: "Shenyang University of Chemical Technology",
    location: "Liaoning, China",
    tuitionRange: "$3,500 - $4,200/year",
    ranking: "Strong Sciences",
    pmdc: true,
    who: true,
    image: "https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?q=80&w=1000&auto=format&fit=crop",
    description: "Excellence in science and technology education.",
  },
  {
    id: 12,
    name: "Hubei University of Arts and Sciences",
    location: "Hubei, China",
    tuitionRange: "$3,000 - $3,800/year",
    ranking: "Comprehensive",
    pmdc: true,
    who: true,
    image: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?q=80&w=1000&auto=format&fit=crop",
    description: "Comprehensive education in historic Xiangyang city.",
  },
  {
    id: 13,
    name: "Hubei University of Science and Technology",
    location: "Hubei, China",
    tuitionRange: "$3,200 - $4,000/year",
    ranking: "Growing Institution",
    pmdc: true,
    who: true,
    image: "https://images.unsplash.com/photo-1509062522246-37559cc792f9?q=80&w=1000&auto=format&fit=crop",
    description: "Modern facilities in the scenic city of Xianning.",
  },
  {
    id: 14,
    name: "Jingangshan University",
    location: "Jiangxi, China",
    tuitionRange: "$2,800 - $3,500/year",
    ranking: "Historic Location",
    pmdc: true,
    who: true,
    image: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?q=80&w=1000&auto=format&fit=crop",
    description: "Located in the revolutionary base area with rich history.",
  },
]

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Ahmed Khan",
    country: "Pakistan",
    flag: "🇵🇰",
    program: "MBBS",
    university: "Yangtze University",
    quote: "GEC made my dream of studying medicine possible. Their team was with me every step - from application to settling in China. The support is exceptional!",
    rating: 5,
    image: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: 2,
    name: "Fatima Al-Rashid",
    country: "Yemen",
    flag: "🇾🇪",
    program: "MBBS",
    university: "Binzhou Medical University",
    quote: "The transparency and honesty of GEC set them apart. No hidden costs, no false promises - just genuine guidance. I recommend them to everyone.",
    rating: 5,
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: 3,
    name: "Emmanuel Okonkwo",
    country: "Ghana",
    flag: "🇬🇭",
    program: "MBBS",
    university: "China Three Gorges University",
    quote: "Being from Ghana, I was worried about studying so far from home. GEC's support made the transition smooth and stress-free. Forever grateful!",
    rating: 5,
    image: "https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: 4,
    name: "Sarah Abdullah",
    country: "Saudi Arabia",
    flag: "🇸🇦",
    program: "MBBS",
    university: "Hubei University of Medicine",
    quote: "Professional service from start to finish. The team's knowledge about Chinese universities is impressive. They found the perfect match for me.",
    rating: 5,
    image: "https://placehold.co/150x150/dcfce7/166534?text=SA",
  },
  {
    id: 5,
    name: "Ibrahim Musa",
    country: "Nigeria",
    flag: "🇳🇬",
    program: "MBBS",
    university: "Nanchang University",
    quote: "From visa guidance to airport pickup, GEC handled everything perfectly. Now I'm successfully studying at one of China's best universities!",
    rating: 5,
    image: "https://placehold.co/150x150/dcfce7/166534?text=IM",
  },
]

export const SCHOLARSHIPS = [
  {
    id: 1,
    name: "Chinese Government Scholarship (CGS)",
    coverage: "Full Tuition + Accommodation + Stipend",
    eligibility: "Excellent academic record, age 18-35",
    description: "The most prestigious scholarship covering all expenses for international students.",
  },
  {
    id: 2,
    name: "Silk Road Scholarship",
    coverage: "Tuition + Partial Living Expenses",
    eligibility: "Students from Belt & Road countries",
    description: "Designed for students from countries along the Silk Road Economic Belt.",
  },
  {
    id: 3,
    name: "Belt and Road Scholarship",
    coverage: "Full/Partial Tuition",
    eligibility: "BRI partner country nationals",
    description: "Supporting educational exchange with Belt and Road Initiative partners.",
  },
  {
    id: 4,
    name: "ANSO Scholarship",
    coverage: "Full Coverage for Research",
    eligibility: "PhD and research students",
    description: "Alliance of International Science Organizations scholarship for researchers.",
  },
  {
    id: 5,
    name: "Provincial Government Scholarships",
    coverage: "Tuition Waiver/Reduction",
    eligibility: "Varies by province",
    description: "Offered by provincial governments like Hubei, Jiangsu, and Guangdong.",
  },
  {
    id: 6,
    name: "University Scholarships",
    coverage: "Tuition Discount/Waiver",
    eligibility: "Merit-based",
    description: "Individual university scholarships based on academic performance.",
  },
]

export const COUNTRIES = [
  {
    id: "pakistan",
    name: "Pakistan",
    flag: "🇵🇰",
    council: "PMDC",
    features: ["Dedicated PMDC guidance", "Urdu-speaking support"],
  },
  {
    id: "yemen",
    name: "Yemen",
    flag: "🇾🇪",
    council: "SYHMC",
    features: ["Arabic support available", "Scholarship assistance"],
  },
  {
    id: "saudi-arabia",
    name: "Saudi Arabia",
    flag: "🇸🇦",
    council: "SCFHS",
    features: ["Premium consultation", "Family guidance"],
  },
  {
    id: "africa",
    name: "African Nations",
    flag: "🌍",
    council: "Various",
    features: ["Ghana, Nigeria, Tanzania & more", "Emerging opportunities"],
  },
]

export const SERVICES = [
  {
    id: 1,
    title: "Admission Consultation",
    icon: "MessageSquare",
    description: "Free initial consultation to understand your goals and recommend the best universities.",
  },
  {
    id: 2,
    title: "Application Assistance",
    icon: "FileText",
    description: "Complete support with document preparation, application submission, and university communication.",
  },
  {
    id: 3,
    title: "Visa Guidance",
    icon: "Plane",
    description: "Comprehensive visa application support including document checklist and interview preparation.",
  },
  {
    id: 4,
    title: "Pre-Departure Support",
    icon: "Briefcase",
    description: "Travel arrangements, packing guidance, and cultural preparation for life in China.",
  },
  {
    id: 5,
    title: "Arrival & Settlement",
    icon: "Home",
    description: "Airport pickup, university registration, accommodation setup, and city orientation.",
  },
  {
    id: 6,
    title: "Test Preparation",
    icon: "BookOpen",
    description: "HSK preparation courses, mock tests, and achievement programs for exam success.",
  },
  {
    id: 7,
    title: "Ongoing Support",
    icon: "Shield",
    description: "Continuous academic guidance, emergency assistance, and career counseling throughout your stay.",
  },
]

export const FAQS = {
  mbbs: [
    {
      question: "Is MBBS from China recognized in Pakistan?",
      answer: "Yes, universities approved by PMDC are recognized. Graduates must pass the National Licensing Examination (NLE) to practice in Pakistan. GEC only works with PMDC-recognized universities.",
    },
    {
      question: "Can I practice in India after MBBS from China?",
      answer: "Only graduates from the 45 MOE-listed universities can appear for FMGE/NExT in India. We provide transparent information about each university's recognition status.",
    },
    {
      question: "What is HSK and do I need it?",
      answer: "HSK (Hanyu Shuiping Kaoshi) is the Chinese proficiency test. Most programs require HSK-4 before clinical years. GEC provides HSK preparation support to help you succeed.",
    },
    {
      question: "What are the living costs in China?",
      answer: "Monthly living costs range from $200-400 depending on city and lifestyle. This includes food, transport, and personal expenses. University canteens offer affordable meals.",
    },
    {
      question: "Is it safe for international students in China?",
      answer: "Yes, China is considered very safe with low crime rates. Universities provide secure campus housing and comprehensive support for international students.",
    },
    {
      question: "Can I work part-time while studying?",
      answer: "Student visas generally don't permit off-campus work. Some universities offer on-campus opportunities like teaching assistants or translators with proper authorization.",
    },
    {
      question: "What happens after I graduate?",
      answer: "You'll need to pass licensing exams in your home country to practice. GEC provides guidance on exam preparation and career pathways to help you succeed.",
    },
    {
      question: "How long is the MBBS program?",
      answer: "The MBBS program in China is typically 6 years: 1 year of Chinese language and basic sciences, 4 years of medical studies, and 1 year of clinical internship.",
    },
    {
      question: "What are the admission requirements?",
      answer: "Requirements include: Age 17-25, high school diploma with science subjects, minimum 60% in Biology/Chemistry/Physics, valid passport, and medical fitness certificate.",
    },
    {
      question: "Are there two intakes per year?",
      answer: "Yes, most Chinese universities offer September (main intake with more seats) and March intakes. Scholarship programs typically only have September intake.",
    },
  ],
}